# Generated by Django 5.1.3 on 2024-11-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('skills', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=250)),
            ],
        ),
    ]
