# Generated by Django 5.1.3 on 2024-11-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_backend_files_frontend_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
